routes/web.php
    //----------------------------Balance-------------------------------------------------------------------------------
    Route::get('get_add_balance_form','Admin\Users\Settings\balanceController@getpayform')->name('get_add_balance_form');
    
    Route::get('get_history_user_transaction','Admin\Users\Settings\balanceController@getHistoryTransaction')->name('get_history_user_transaction');
    Route::get('get_history_user_balls','Admin\Users\Settings\balanceController@getHistoryBalls')->name('get_history_user_balls');
    
    //Route::post('orders_s_anydata/export','Admin\Statistics\ordersController@anyData');
    
    Route::resource('mybalance', 'Admin\Users\Settings\balanceController');
    
    //---------------------------------Рефералка------------------------------------------------------------------------
    Route::resource('refsystem', 'Admin\Referals\referalController');
    Route::resource('refrules', 'Admin\Referals\referalRulesController');
    Route::resource('refhistory', 'Admin\Referals\referalHistoryController');
    
    //------------------------------------------------------------------------------------------------------------------
    Route::get('get_all_api', 'Api\apiMediascanController@getNewID');
    // -------------------- Все пути  Админа ---------------------------------------------------------------------------
    
    //
    Route::resource('all_admin_referalsActivity', 'Admin\PersonaArea\referalsAdminActivityController');
    Route::resource('all_admin_financeActivity', 'Admin\PersonaArea\financeAdminActivityController');
    
    
    Route::resource('all_lecturer_financeActivity', 'Admin\PersonaArea\financeLecturerActivityController');
    
    //Управление кадетами
    Route::resource('cadet', 'Admin\Users\Cadet\cadetController'); 
    
    Route::resource('curator', 'Admin\Users\Curator\curatorController');                                               
                                                         
    Route::resource('lectors', 'Admin\Users\Lector\lectorController');
    Route::resource('curses', 'Admin\Curses\cursesController');
    Route::resource('language', 'Admin\Language\languageController');
    
    Route::resource('message', 'Admin\Message\messageController');
    Route::post('message_admin', 'Admin\Message\messageController@messageadmin')->name('message_admin');
    Route::post('delete_multi_message', 'Admin\Message\messageController@delete_multi_message')->name('delete_multi_message');
    
    Route::resource('profile', 'Admin\Users\Settings\profileSettingsController');
    Route::resource('mentor_settings', 'Admin\Educational\mentorsSettings');
    Route::resource('group_user', 'Admin\Users\Settings\userGroupController');
    Route::resource('roles_user', 'Admin\Users\Settings\userRolesController');
       
    //-------------------------------------------- блоки курсов * новое
    Route::post('add_course_to_block/{block_id}','Admin\Curses\Block\blockController@add_course_to_block')->name('add_course_to_block');
    Route::post('del_course_to_block/{block_id}','Admin\Curses\Block\blockController@del_course_to_block')->name('del_course_to_block');
    Route::resource('admin_block', 'Admin\Curses\Block\blockController', ['except' => [ 'store']]);
    
    
    Route::resource('ablog', 'Admin\Blog\blogController');
    Route::resource('atags', 'Admin\Tag\tagController');
    
    Route::post('blog/like/{id}', ['as' => 'blog.like', 'uses' => 'LikeController@likeBlog']);
    
    //Gilbo blog
    Route::get('blog_gilbo/search', ['as' => 'ablog_gilbo.search', 'uses' => 'Users\Blogs\gilboController@search']  );
    Route::resource('blog_gilbo','Users\Blogs\gilboController');
    
    //Lecturer blog
    Route::get('blog_lecturer/search', ['as' => 'ablog_lecturer.search', 'uses' => 'Users\Blogs\lecturerController@search']  );
    Route::resource('blog_lecturer','Users\Blogs\lecturerController');
    
    //Gaypark blog
    Route::get('blog_gaidpark/search', ['as' => 'ablog_gaypark.search', 'uses' => 'Users\Blogs\gayparkController@search']  );
    Route::resource('blog_gaidpark','Users\Blogs\gayparkController');
    
    //MAIN USER BLOG controller
    Route::get('blog/search', ['as' => 'ablog.search', 'uses' => 'Users\blogController@search']  );
    Route::resource('blog', 'Users\blogController');
    
    Route::post('comment/like/{id}', ['as' => 'comment.like', 'uses' => 'LikeController@likeComment']);
    Route::get('comment_list/{id_blog}', ['uses' => 'CommentController@index', 'as' => 'comment_list']);
    //
    Route::post('comment_delete/{id_blog}/delete/{id_comment}', ['uses' => 'CommentController@destroy', 'as' => 'comment_delete']);
    Route::post('comment', ['uses' => 'CommentController@store', 'as' => 'comment']);
    
    //лекции для админа и лектора
    Route::resource('prelection', 'Admin\Prelection\prelectionController');
    Route::post('multiple_delete_prelection', 'Admin\Prelection\prelectionController@multipleDelete')
        ->name('multiple_delete_prelection');
    Route::post('prelection_destr/{id}','Admin\Prelection\prelectionController@destroy')
        ->name('prelection_destr');
    //--------------------------Новости---------------------------------------------------------------------------------
    Route::resource('news', 'Admin\News\newsController');
    Route::resource('video_news', 'Admin\News\videoNewsController');
    Route::resource('video_instruction', 'Admin\News\videoInstructionController');
    
    
    // новостные статьи для авторизированных пользователей
    Route::get('unewsv/{id}','Users\newsController@videoNews')->name('unewsv');
    Route::resource('unews','Users\newsController', ['only' => ['index','show']]);
    
    //------------------------------------------------------------------------------------------------------------------
    //-------------------------------Меропреятия и семинары ------------------------------------------------------------
    Route::resource('admin_events', 'Admin\Doings\eventsController');
    //------------------------------------------------------------------------------------------------------------------
    
    //Billing statistic
    Route::get('biling_statistics/getAjaxData','Admin\Statistics\bilingController@getAjaxData')->name('biling_statistics.getAjaxData');
    Route::post('biling_statistics/getAjaxData/export','Admin\Statistics\bilingController@getAjaxData');
    Route::resource('biling_statistics', 'Admin\Statistics\bilingController');

        Route::get('admin_repl_statistics', 'Admin\Statistics\bilingController@adminReplStatistics')
        ->name('admin_repl_statistics');

    Route::post('search_email_repl_admin','Admin\Statistics\bilingController@emailSearchUser')
        ->name('search_email_repl_admin');

    Route::post('del_order_admin_prel/{id}','Admin\Statistics\bilingController@delReplOrder')->name('del_order_admin_prel');
    
    
    //Order Statistic
    
    Route::resource('orders_statistics', 'Admin\Statistics\ordersController');

    Route::get('orders_s_anydata','Admin\Statistics\ordersController@anyData')->name('orders_s_anydata');
    Route::post('orders_s_anydata/export','Admin\Statistics\ordersController@anyData');
    
    Route::post('search_email_orders_admin','Admin\Statistics\ordersController@emailSearchUser')
        ->name('search_email_orders_admin');
    
    
    //balls statistic
    Route::get('balls_statistics/getAjaxData','Admin\Statistics\ballsController@getAjaxData')->name('balls_statistics.getAjaxData');
    Route::post('balls_statistics/getAjaxData/export','Admin\Statistics\ballsController@getAjaxData');
    Route::resource('balls_statistics', 'Admin\Statistics\ballsController');
    
    //CONVERTERS
    Route::post('form_converter_ball_to_kell','Users\Converters\ballToKelController@forInclude')->name('form_converter_ball_to_kell');
    
    
    
    //учебная аудитория
    Route::resource('educational_audience', 'Users\Educational\audienceController');
    
    //каталог курсов
    Route::resource('lectures_catalog', 'Users\Cataloglectures\cataloglecturesController');
    
    //вебинарная комната
    Route::resource('webinars_room', 'Users\Webinars\webinarsController');
    //семинары
    Route::resource('advice_room', 'Users\Advice\adviceController');
    //faq
    Route::resource('faq', 'Users\Faq\faqController');

//    Route::resource('reference_statistics', 'Admin\Statistics\referenceStatisticsController');
//    Route::post('search_ref_orders_admin','Admin\Statistics\referenceStatisticsController@emailSearchUser')
//        ->name('search_ref_orders_admin');

    
    //Работаем с подписчиками ----------------------------------------------------------------------------------------
        //проверить наличие подписчика по email
        Route::post('subscribers/check/{mail}', 'Admin\Subscribers\subscribersController@check')->name('subscribers.check');
//        //сменить статус подписки
//        Route::post('subscribers/change_status/{id}', 'Admin\Subscribers\subscribersController@changeStatus')->name('subscribers.change_status');
        //SubscibersDataTable
        Route::get('subscribers/getAjaxData','Admin\Subscribers\subscribersController@getAjaxData')->name('subscribers.getAjaxData');
        Route::post('subscribers/getAjaxData/export','Admin\Subscribers\subscribersController@getAjaxData');
        //основной роутер
        Route::resource('subscribers', 'Admin\Subscribers\subscribersController');
    
    
    //----------------------Test----------------------------------------------------------------------------------------
    Route::resource('test', 'Admin\Tasks\testController');
    Route::get('fill_test/{id}', 'Admin\Tasks\testController@fillTest')->name('fill_test');
    Route::get('delete_question/{id}', 'Admin\Tasks\testController@deleteQuestion')->name('delete_question');

app/Http/Controllers/Admin/Tag/tagController.php
<?php

namespace App\Http\Controllers\Admin\Tag;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use Illuminate\Support\Facades\Auth;

use Mcamara\LaravelLocalization\Facades\LaravelLocalization;

use App\Models\Blog\Blog;

use Lecturize\Tags\Models\Tag;
use Lecturize\Tags\Models\Taggable;

class tagController extends Controller
{
    /**
     * Только админы
     */
    public function __construct()
    {
        $this->middleware('onlyadmin');
    }
    
    /**
     * список тегов
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\RedirectResponse|\Illuminate\View\View
     */
    public function index()
    {
        $tags = Tag::paginate(10);
        return view('Admin.admin.tag.list', compact('tags'));
    }

    /**
     * Метод вывода пердставления для создания тега
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\RedirectResponse|\Illuminate\View\View
     */
    public function create()
    {
        return view('Admin.admin.tag.create');
    }

    /**
     * Метод созранения тега в таблицу БД
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'tag'=>'required|unique:tags,tag'
        ]);
        
        $model = new Tag;
        $model->tag = trim($request->input('tag'));
        $model->save();


        return redirect(route('atags.index'))->with('success','Тег успешно добавлен!');

    }

    /**
     * Метод вывода представления для редактирования тега
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\RedirectResponse|\Illuminate\View\View
     */
    public function edit($id)
    {

        $tag = Tag::find($id);

        if(!$tag){
            return back()->with('warning','Ошибка при поиске тега!');
        }

        return view('Admin.admin.tag.edit',compact('tag'));

    }

    /**
     * Метод обновления тега
     * @param Request $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Request $request, $id)
    {
        $tag = Tag::find($id);
        if(!$tag){
            return back()->with('warning','Тег не найден!');
        }
        $this->validate($request,[
            'tag'=>'required|unique:tags,tag,'.$id
        ]);

        $tag->tag = trim($request->input('tag'));
        $tag->save();
        
        return redirect(route('atags.index'))->with('success','Тег успешно отредактирован!');
    }

    /**
     * Метод удаления тега
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        $tag = Tag::find($id);
        if(!$tag){
            return back()->with('warning','Тег не найден!');
        }

        $tag->delete();
        return back()->with('success','Тег успешно удален!');
    }
}

resources/views/Admin/admin/tag/create.blade.php
@extends('layouts.admin')

@section('content')
    <div class="col-md-12">
        <header class="big-header text-center">Форма добавления тега</header>
        <div class="panel">

            {!! Form::open(array('route'=>'atags.store', 'method'=>'POST','enctype'=>'multipart/form-data'))!!}
            
            <div class="form-group">
                {!! Form::label('tag','Название тега',array_merge(['class'=>'control-label'])) !!}
                {!! Form::text('tag',null,array_merge(['class'=>'form-control','required','placeholder'=>'Название тега'])) !!}
            </div>

            <div class="form-group">
                {!! Form::submit('Сохранить',['class'=>'btn btn-success']) !!}
                <a href="{{route('atags.index')}}" class="btn btn-info">Назад</a>
            </div>
            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/Admin/admin/tag/edit.blade.php
@extends('layouts.admin')

@section('content')
    <div class="col-md-12">
        <header class="big-header text-center">Форма рдекатирования тега</header>
        <div class="panel">
            {!! Form::open(array('route'=>['atags.update',$tag->id], 'method'=>'POST','enctype'=>'multipart/form-data'))!!}
            {{ method_field('PUT') }}

            <div class="form-group">
                {!! Form::label('tag','Название тега',array_merge(['class'=>'control-label'])) !!}
                {!! Form::text('tag',$tag->tag,array_merge(['class'=>'form-control','required','placeholder'=>'Название тега'])) !!}
            </div>

            <div class="form-group">
                {!! Form::submit('Сохранить',['class'=>'btn btn-success']) !!}
                <a href="{{route('atags.index')}}" class="btn btn-info">Назад</a>
            </div>
            {!! Form::close() !!}

        </div>
    </div>
@endsection

resources/views/Admin/admin/tag/list.blade.php
@extends('layouts.admin')

@section('content')
    <div class="col-md-12">
        <header class="big-header text-center">Теги SDO</header>
        <div class="form-group">
            <a href="{{route('atags.create')}}" class="btn btn-success"><i class="fa fa-plus"></i> Добавить тег</a>
        </div>
        <div class="row">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Тег</th>
                        <th>slug</th>
                        <th>suggest</th>
                        <th>{{trans('content.actions')}}</th>
                    </tr>
                </thead>
            @foreach($tags as $tag)
                <tr>
                  <td>{{ $tag->id }}</td>
                  <td>{{ $tag->tag }}</td>
                  <td>{{ $tag->slug }}</td>
                  <td>{{ $tag->suggest }}</td>
                  <td><a href="{{route('atags.edit',$tag->id)}}" class="btn btn-info" title="Редактировать статью">
                                <i class="fas fa-pencil-alt"></i></a>
                            {!! Form::open(array('route'=>['atags.destroy',$tag->id],'method'=>'DELETE','class'=>'inline-block')) !!}
                            {!! Form::button('<i class="fa fa-times"></i>',['class'=>'btn btn-danger','type'=>'submit','onclick'=>'return checkDelete()','title'=>'Удалить']) !!}
                            {!! Form::close() !!}
                  
                  </td>
                </tr>
            @endforeach
            </table>
        </div>
        <div class="row">
            {{ $tags->links() }}
        </div>
    </div>
@endsection