routes/web.php
//GayPark blog
Route::get('gaidpark','Users\Blogs\gayparkController@free_index')->name('front_blog_gaypark');
Route::get('gaidpark/{slug}', 'Users\Blogs\gayparkController@free_show')->name('front_blog_gaypark_show');
Route::get('gaidpark_search', 'Users\Blogs\gayparkController@search' )->name('front_blog_gaypark_search');

//конкретно для фронта
Route::post('add_new_subscribers','Admin\Subscribers\subscribersController@store')->name('add_new_subscribers');

Route::get('comments_load/{id_blog}', ['uses' => 'CommentController@comments_load', 'as' => 'comments_load']);

Route::group(['middleware' => 'admin', 'prefix' => 'admin'], function () {
    //--------------------- Личный кабинет -----------------------------------------------------------------------------
    
    Route::any('/', function () { return redirect()->route('/personal_area'); });//fix Рабочий кабинет
    Route::get('/personal_area', 'Admin\adminHomeController@index')->name('/personal_area');//Рабочий кабинет
    
    Route::post('change_profile_avatar/{id}', 'Admin\Users\Settings\profileSettingsController@changeAvatar')
        ->name('change_profile_avatar');
    Route::post('change_prof/{id}', 'Admin\Users\Settings\profileSettingsController@changeProf')
        ->name('change_prof');
    Route::post('change_user_data/{id}', 'Admin\Users\Settings\profileSettingsController@changeUserData')
        ->name('change_user_data');
    Route::post('change_user_email/{id}', 'Admin\Users\Settings\profileSettingsController@changeUserEmail')
        ->name('change_user_email');
    //--------------------------------DELETE AVATAR---------------------------------------------------------------------
    Route::post('delete_avatar', 'Admin\Users\Settings\profileSettingsController@deleteAvatar')->name('delete_avatar');
    //------------------------------------------------------------------------------------------------------------------
    Route::resource('connection_mentors', 'Admin\Educational\connectionController');
    Route::get('add_connect_mentor/{id}', 'Admin\Educational\connectionController@addConnection')
        ->name('add_connect_mentor');
    Route::get('show_mail', 'Admin\Users\Chats\chatController@index')->name('show_mail');
    Route::get('send_mail_user', 'Admin\Users\Chats\chatController@sendMails')->name('send_mail_user');
    Route::get('more_mail/{id}', 'Admin\Users\Chats\chatController@show')->name('more_mail');
    Route::post('answer_users', 'Admin\Users\Chats\chatController@store')->name('answer_users');
    
    Route::resource('user_callback_chats', 'Admin\Users\Chats\chatController');//общение с администратором
    
//    Route::get('create_mail_user', 'Admin\Users\Chats\chatController@create')->name('create_mail_user');


    //----------------------------Balance-------------------------------------------------------------------------------
    Route::get('get_add_balance_form','Admin\Users\Settings\balanceController@getpayform')->name('get_add_balance_form');
    
    Route::get('get_history_user_transaction','Admin\Users\Settings\balanceController@getHistoryTransaction')->name('get_history_user_transaction');
    Route::get('get_history_user_balls','Admin\Users\Settings\balanceController@getHistoryBalls')->name('get_history_user_balls');
    
    //Route::post('orders_s_anydata/export','Admin\Statistics\ordersController@anyData');
    
    Route::resource('mybalance', 'Admin\Users\Settings\balanceController');
    
    //---------------------------------Рефералка------------------------------------------------------------------------
    Route::resource('refsystem', 'Admin\Referals\referalController');
    Route::resource('refrules', 'Admin\Referals\referalRulesController');
    Route::resource('refhistory', 'Admin\Referals\referalHistoryController');
    
    //------------------------------------------------------------------------------------------------------------------
    Route::get('get_all_api', 'Api\apiMediascanController@getNewID');
    // -------------------- Все пути  Админа ---------------------------------------------------------------------------
    
    //
    Route::resource('all_admin_referalsActivity', 'Admin\PersonaArea\referalsAdminActivityController');
    Route::resource('all_admin_financeActivity', 'Admin\PersonaArea\financeAdminActivityController');
    
    
    Route::resource('all_lecturer_financeActivity', 'Admin\PersonaArea\financeLecturerActivityController');
    
    //Управление кадетами
    Route::resource('cadet', 'Admin\Users\Cadet\cadetController'); 
    
    Route::resource('curator', 'Admin\Users\Curator\curatorController');                                               
                                                         
    Route::resource('lectors', 'Admin\Users\Lector\lectorController');
    Route::resource('curses', 'Admin\Curses\cursesController');
    Route::resource('language', 'Admin\Language\languageController');
    
    Route::resource('message', 'Admin\Message\messageController');
    Route::post('message_admin', 'Admin\Message\messageController@messageadmin')->name('message_admin');
    Route::post('delete_multi_message', 'Admin\Message\messageController@delete_multi_message')->name('delete_multi_message');
    
    Route::resource('profile', 'Admin\Users\Settings\profileSettingsController');
    Route::resource('mentor_settings', 'Admin\Educational\mentorsSettings');
    Route::resource('group_user', 'Admin\Users\Settings\userGroupController');
    Route::resource('roles_user', 'Admin\Users\Settings\userRolesController');
       
    //-------------------------------------------- блоки курсов * новое
    Route::post('add_course_to_block/{block_id}','Admin\Curses\Block\blockController@add_course_to_block')->name('add_course_to_block');
    Route::post('del_course_to_block/{block_id}','Admin\Curses\Block\blockController@del_course_to_block')->name('del_course_to_block');
    Route::resource('admin_block', 'Admin\Curses\Block\blockController', ['except' => [ 'store']]);
    
    
    Route::resource('ablog', 'Admin\Blog\blogController');
    Route::resource('atags', 'Admin\Tag\tagController');
    
    Route::post('blog/like/{id}', ['as' => 'blog.like', 'uses' => 'LikeController@likeBlog']);
    
    //Gilbo blog
    Route::get('blog_gilbo/search', ['as' => 'ablog_gilbo.search', 'uses' => 'Users\Blogs\gilboController@search']  );
    Route::resource('blog_gilbo','Users\Blogs\gilboController');
    
    //Lecturer blog
    Route::get('blog_lecturer/search', ['as' => 'ablog_lecturer.search', 'uses' => 'Users\Blogs\lecturerController@search']  );
    Route::resource('blog_lecturer','Users\Blogs\lecturerController');
    
    //Gaypark blog
    Route::get('blog_gaidpark/search', ['as' => 'ablog_gaypark.search', 'uses' => 'Users\Blogs\gayparkController@search']  );
    Route::resource('blog_gaidpark','Users\Blogs\gayparkController');
    
    //MAIN USER BLOG controller
    Route::get('blog/search', ['as' => 'ablog.search', 'uses' => 'Users\blogController@search']  );
    Route::resource('blog', 'Users\blogController');
    
    Route::post('comment/like/{id}', ['as' => 'comment.like', 'uses' => 'LikeController@likeComment']);
    Route::get('comment_list/{id_blog}', ['uses' => 'CommentController@index', 'as' => 'comment_list']);
    //
    Route::post('comment_delete/{id_blog}/delete/{id_comment}', ['uses' => 'CommentController@destroy', 'as' => 'comment_delete']);
    Route::post('comment', ['uses' => 'CommentController@store', 'as' => 'comment']);
    
    //лекции для админа и лектора
    Route::resource('prelection', 'Admin\Prelection\prelectionController');
    Route::post('multiple_delete_prelection', 'Admin\Prelection\prelectionController@multipleDelete')
        ->name('multiple_delete_prelection');
    Route::post('prelection_destr/{id}','Admin\Prelection\prelectionController@destroy')
        ->name('prelection_destr');
    //--------------------------Новости---------------------------------------------------------------------------------
    Route::resource('news', 'Admin\News\newsController');
    Route::resource('video_news', 'Admin\News\videoNewsController');
    Route::resource('video_instruction', 'Admin\News\videoInstructionController');
    
    
    // новостные статьи для авторизированных пользователей
    Route::get('unewsv/{id}','Users\newsController@videoNews')->name('unewsv');
    Route::resource('unews','Users\newsController', ['only' => ['index','show']]);
    
    //------------------------------------------------------------------------------------------------------------------
    //-------------------------------Меропреятия и семинары ------------------------------------------------------------
    Route::resource('admin_events', 'Admin\Doings\eventsController');
    //------------------------------------------------------------------------------------------------------------------
    
    //Billing statistic
    Route::get('biling_statistics/getAjaxData','Admin\Statistics\bilingController@getAjaxData')->name('biling_statistics.getAjaxData');
    Route::post('biling_statistics/getAjaxData/export','Admin\Statistics\bilingController@getAjaxData');
    Route::resource('biling_statistics', 'Admin\Statistics\bilingController');

        Route::get('admin_repl_statistics', 'Admin\Statistics\bilingController@adminReplStatistics')
        ->name('admin_repl_statistics');

    Route::post('search_email_repl_admin','Admin\Statistics\bilingController@emailSearchUser')
        ->name('search_email_repl_admin');

    Route::post('del_order_admin_prel/{id}','Admin\Statistics\bilingController@delReplOrder')->name('del_order_admin_prel');
    
    
    //Order Statistic
    
    Route::resource('orders_statistics', 'Admin\Statistics\ordersController');

    Route::get('orders_s_anydata','Admin\Statistics\ordersController@anyData')->name('orders_s_anydata');
    Route::post('orders_s_anydata/export','Admin\Statistics\ordersController@anyData');
    

app/Http/Controllers/Admin/Statistics/ballsController.php
<?php

namespace App\Http\Controllers\Admin\Statistics;

use App\Models\Billing\Balls;
use App\DataTables\AdminBallsDataTable;

use App\Http\Controllers\Controller;



class ballsController extends Controller
{
    
    /**
     * Только админы
     */
    public function __construct()
    {
        $this->middleware('onlyadmin');
    }
    
    /**
     * Метод вывода статистики
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\RedirectResponse|\Illuminate\View\View
     */
    public function index()
    {
        return view('Admin.statistics.balls.index');
    }
    
    
    /**
     * Process datatables ajax request.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function getAjaxData(AdminBallsDataTable $dataTable)
    {
        return $dataTable->render('dataTables.ordersStatistic');
    }

    
   
    /**
     * Метод удаления записи о баллах
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {

        $order = Balls::find($id);
        if(!$order){
            return back()->with('warning','Данная запись не найдена!');
        }
        $order->delete();
        return back()->with('success','Запись успешно удалена!');
    }

}

app/Http/Controllers/Admin/Statistics/bilingController.php
<?php

namespace App\Http\Controllers\Admin\Statistics;

use App\Models\Billing\Billing;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

use App\DataTables\BillingDataTable;

class bilingController extends Controller
{
    
    /**
     * Только админы
     */
    public function __construct()
    {
        $this->middleware('onlyadmin');
    }
    
    /**
     * Метод вывода данных о пополнении пользователями личных счетов
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\RedirectResponse|\Illuminate\View\View
     */
    public function index()
    {
//        if (Auth::user()->isAdmin() or Auth::user()->isLecturer()) {
//            $billing_orders = Billing::where('type_replenishment',0)->orderBy('id','desc')->paginate(15);
//            return view('Admin.statistics.bilingStatistics', compact('billing_orders'));
//        } else {
//            // Реализовать отправку сообщения администратору о взломе.
//            return back()->with('warning', trans('message.hack_message'));
//        }
        return view('Admin.statistics.orders.index');
    }
    
    /**
     * Process datatables ajax request.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function getAjaxData(BillingDataTable $dataTable)
    {
        return $dataTable->render('dataTables.billing.index');
    }
    
    
    

    /**
     * Метод удаления записи с таблицы  о пополнении личного счета на сайте.
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {

        $billing_order = Billing::find($id);
        $billing_order->delete();
        return back()->with('success','Запись успешно удалена');

    }

    public function adminReplStatistics(){
        $billing_orders = Billing::where('type_replenishment',1)
            ->orderBy('created_at','DESC')
            ->paginate(15);
        return view('Admin.statistics.billing_replen_admin',compact('billing_orders'));
    }

    public function delReplOrder($id){
            $billing_order = Billing::find($id);
            $billing_order->delete();
            return back()->with('success','Пополнение отменено успешно!');
    }

    public function emailSearchUser(Request $request){
        if(Auth::user()){
            if($request->email_user){
                $this->validate($request,[
                    'email_user'=>'required|email|max:255|'
                ]);
                $user = User::where('email',$request->email_user)->first();
                if(!$user){
                return redirect(route('admin_repl_statistics'))->with('warning','Пользователь с таким Email не найден');
                }
                $billing_orders = Billing::where('type_replenishment',1)
                    ->where('user_id',$user->id)
                    ->orderBy('created_at','DESC')
                    ->get();
                return view('Admin.statistics.billing_replen_admin',compact('billing_orders'));
            }
        }else{
            return back()->with('warning', trans('message.hack_message'));
        }
    }
}

resources/views/Admin/statistics/bilingStatistics.blade.php
@extends('layouts.admin')

@section('content')
    <div class="col-md-12">
        <header class="big-header">Статистика пополнений счетов пользователей</header>
        <div class="row">
            <div class="col-lg-12">
                <div class="panel">
                    <h4 class="text-center">Статистика</h4>
                    <hr>
                    <div class="row">
                        <div class="col-md-6">
                            <form action="{{route('search_email_billig')}}" method="GET" class="input-group">
                                <input type="hidden" name="_token" value="{{csrf_token()}}">
                                <input type="text" class="form-control" name="email"
                                       placeholder="Сортировка по email" required>
                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-blue  btn-icon"
                                    ><i class="fa fa-search"
                                        aria-hidden="true"></i></button>
                                </div>
                            </form>
                        </div>
                        <div class="col-md-6">
                            <form action="{{route('search_inv_billig')}}" method="GET" class="input-group">
                                <input type="hidden" name="_token" value="{{csrf_token()}}">
                                <input type="text" class="form-control" name="inv"
                                       placeholder="Сортировка по номеру платежа" required>
                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-blue  btn-icon"><i class="fa fa-search"
                                                                                            aria-hidden="true"></i>
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                    <table class="table table-responsive">
                        <thead>
                        <tr>
                            <th>№</th>
                            <th>Пользователь</th>
                            <th>Email</th>
                            <th>Сумма</th>
                            <th>Валюта</th>
                            <th>Номер платежа</th>
                            <th>Описание</th>
                            <th>Дата</th>
                        </tr>
                        </thead>
                        <tbody class="billing">
                        <?php $i = 1;?>
                        @if(count($billing_orders)!= 0)
                            @foreach($billing_orders as $order)
                                <tr>
                                    <td>{{$i++}}</td>
                                    <td>{{ isset($order->user)?$order->user->name:$order->user_id }}</td>
                                    <td>{{ isset($order->user)?$order->user->email:$order->user_id }}</td>
                                    <td>{{$order->transfer_sum}}</td>
                                    <td>{{$order->currency}}</td>
                                    <td>{{$order->number_inv}}</td>
                                    <td>{{mb_strimwidth($order->desc,0,50,'...')}}</td>
                                    <td>{{date('d.m.Y', strtotime($order->created_at))}}</td>
                                    @if(Auth::user()->isAdmin())
                                        <td><i class="fa fa-lock" aria-hidden="true"></i> 
                                            <!-- 
                                            {!! Form::open(array('route'=>['biling_statistics.destroy',$order->id],'method'=>'DELETE')) !!}
                                            <button type="submit" class="btn btn-danger">Удалить</button>
                                            {!! Form::close()!!}
                                            -->
                                        </td>
                                    @else
                                        <td><i class="fa fa-lock" aria-hidden="true"></i></td>
                                    @endif
                                </tr>
                            @endforeach
                        @else
                            На данный момент нет пополнений счетов.
                        @endif
                        </tbody>
                    </table>

                    {{ $billing_orders->links() }}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/Admin/statistics/billing_replen_admin.blade.php
@extends('layouts.admin')

@section('content')
    <div class="col-md-12">
        <header class="big-header text-center">Статистика пополнений администратором SDO</header>
        <div class="panel">
            <h4 class="text-center">Статистика</h4>
            <div class="row">
                <div>
                    <form action="{{route('search_email_repl_admin')}}" method="post">
                        <div class="input-group">
                        <span class="input-group-btn">
                            <a type="submit" class="btn btn-danger" href="{{route('admin_repl_statistics')}}">Сбросить</a>
                        </span>
                            <input type="hidden" name="_token" value="{{csrf_token()}}">
                            <input type="email" class="form-control" name="email_user" id="searchEmail"
                                   placeholder="Поиск по почте">
                            <span class="input-group-btn">
                            <button class="btn btn-blue" type="submit">Поиск</button>
                        </span>
                        </div>
                    </form>
                </div>
            </div>
            <table class="table table-responsive">
                <thead>
                <tr>
                    <th>№</th>
                    <th>Пользователь</th>
                    <th>Email</th>
                    <th>Сумма</th>
                    <th>Валюта</th>
                    <th>Описание</th>
                    <th>Админ</th>
                    <th>Дата</th>
                    <th>Действие</th>
                </tr>
                </thead>
                <tbody>
                <?php $i = 1;?>
                @if(count($billing_orders)!= 0)
                    @foreach($billing_orders as $order)
                        <tr>
                            <td>{{$i++}}</td>
                            <td>{{ isset($order->user)?$order->user->name:$order->user_id }}</td>
                            <td>{{ isset($order->user)?$order->user->email:$order->user_id }}</td>
                            <td>{{$order->transfer_sum}}</td>
                            <td>{{$order->currency}}</td>
                            <td>{{$order->desc}}</td>
                            @if( isset($order->admin) )
                                <td>{{$order->admin->name}}</td>
                            @else
                                <td></td>
                            @endif
                            <td>{{$order->created_at}}</td>
                            <td>
                                {!! Form::open(array('route'=>['del_order_admin_prel',$order->id],'method'=>'post')) !!}
                                <button type="submit" class="btn btn-danger">Удалить</button>
                                {!! Form::close()!!}
                            </td>

                        </tr>
                    @endforeach
                @endif
                </tbody>
            </table>
            {{ $billing_orders->links() }}
        </div>
    </div>
@endsection

resources/views/Admin/statistics/ordersStatistics.blade.php
@extends('layouts.admin')

@section('content')

<link rel="stylesheet" href="{{ asset('css/datatables.css') }}">


    <div class="col-md-12">
        <header class="big-header text-center">Статистика о покупках курсов</header>        
        <div class="row">
            <table class="table table-responsive"  id="users-table-orders">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Покупатель</th>
                        <th>Email</th>
                        <th>Курс</th>
                        <th width="70">Сумма</th>
                        <th>Бонус лектора</th>
                        <th>Дата</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                </tfoot>
            </table>
        </div>
        
    </div>



@endsection

@section('script')
<script src="{{ asset('js/datatables/datatables.js') }}"></script>
<script src="{{ asset('js/datatables/dataTables.buttons.js') }}"></script>
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>
    <script>
      $(document).ready(function() {          
            var table = $('#users-table-orders').DataTable({
                processing: true,
                serverSide: true,
                displayLength: 10,
                autoWidth: false,
                ajax:{
                    "url": "{!! route('orders_s_anydata') !!}",
                    "data": function ( data ) {
                        //data._token = "{{ csrf_token() }}";
                    }
                },
                columns: [
                    {data: 'id', name: 'id', searchable: false},
                    {data: 'user.name', name: 'user.name'},
                    {data: 'user.email', name: 'user.email'},
                    {data: 'course.lang.name_trans', name: 'course.lang.name_trans'},
                    {data: 'sum', name: 'sum' , "type": "numeric"},
                    {data: 'lecture_sum', name: 'lecture_sum'},
                    {data: 'created_at', name: 'created_at'},
                ],
                initComplete: function () {
                    this.api().columns().columns([1, 2, 3, 6]).every(function () {
                        var column = this;
                        var input = document.createElement("input");
                        $(input).appendTo($(column.footer()).empty())
                        .on('change', function () {
                            column.search($(this).val(), false, false, true).draw();
                        });
                    });
                },
                language: {
                    processing: "Поиск в базе",
                    info:       "показано с _START_ по _END_ покупок из _TOTAL_",
                    infoEmpty:  "нет покупок",
                    infoFiltered: "(фильтр по _MAX_ покупках)",
                    lengthMenu: "По _MENU_ покупок",
                },
            });
            
            new $.fn.dataTable.Buttons( table, {
                buttons: [
                    'postExcel', 'postCsv'
                ]
            } );
            
            table.buttons().container().prependTo( $('.col-sm-6:eq(0)', table.table().container() ) );

        });

    </script>
@endsection

resources/views/Admin/statistics/sortBilling.blade.php
@extends('layouts.admin')

@section('content')
    <div class="col-md-12">
        @if(isset($user->name))
            <header class="big-header text-center">Статистика пополнений счетов пользователя {{$user->name}}</header>
        @else
            <header class="big-header text-center">Статистика пополнений </header>
        @endif
        <div class="row">
            <div class="col-lg-12">
                <div class="panel">
                    <h4 class="text-center">Статистика</h4>
                    <a class="btn btn-blue" href="{{route('biling_statistics.index')}}">Общий список</a>
                    <hr>
                    <div class="row">
                        <div class="col-md-6">
                            <form action="{{route('search_email_billig')}}" method="GET" class="input-group">
                                <input type="hidden" name="_token" value="{{csrf_token()}}">
                                <input type="text" class="form-control" name="email" id="searchItem"
                                       placeholder="Сортировка по email">
                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-blue  btn-icon"
                                    ><i class="fa fa-search"
                                        aria-hidden="true"></i></button>
                                </div>
                            </form>
                        </div>
                        <div class="col-md-6">
                            <form action="{{route('search_inv_billig')}}" method="GET" class="input-group">
                                <input type="hidden" name="_token" value="{{csrf_token()}}">
                                <input type="text" class="form-control" name="item" id="searchItem"
                                       placeholder="Сортировка по номеру платежа">
                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-blue  btn-icon"><i class="fa fa-search"
                                                                                            aria-hidden="true"></i>
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                    <table class="table table-responsive">
                        <thead>
                        <tr>
                            <th>№</th>
                            <th>Пользователь</th>
                            <th>Email</th>
                            <th>Сумма</th>
                            <th>Валюта</th>
                            <th>Номер платежа</th>
                            <th>Описание</th>
                            <th>Дата</th>
                        </tr>
                        </thead>
                        <tbody class="billing">
                        <?php $i = 1;?>
                        @foreach($orders as $order)
                            <tr id="{{$order->user->name}}">
                                <td>{{$i++}}</td>
                                <td>{{$order->user->name}}</td>
                                <td>{{$order->user->email}}</td>
                                <td>{{$order->transfer_sum}}</td>
                                <td>{{$order->currency}}</td>
                                <td>{{$order->number_inv}}</td>
                                <td>{{mb_strimwidth($order->desc,0,50,'...')}}</td>
                                <td>{{date('d.m.Y', strtotime($order->created_at))}}</td>
                                @if(Auth::user()->isAdmin())
                                    <td> {!! Form::open(array('route'=>['biling_statistics.destroy',$order->id],'method'=>'DELETE')) !!}
                                        <button type="submit" class="btn btn-danger">Удалить</button>
                                        {!! Form::close()!!}</td>
                                @else
                                    <td><i class="fa fa-lock" aria-hidden="true"></i></td>
                                @endif
                            </tr>
                        @endforeach
                        </tbody>
                    </table>


                </div>
            </div>
        </div>
    </div>
@endsection